version: '2.0'
services:
  db:
    image: postgres:12.4-alpine
    restart: unless-stopped
    volumes:
      - database-volume:/var/lib/postgresql/data
      - ./init-users.sh:/docker-entrypoint-initdb.d/init-users.sh
    environment:
      - POSTGRES_PASSWORD=postgres
  user-management:
    image: flotte-docker-registry.spdns.org/flotte-user-managment
    links:
      - "db:database"
    mem_limit: "1000000000"
    restart: unless-stopped
    environment:
      - POSTGRES_CONNECTION_URL=postgres://fuser_management:passwordofuserserver@database/user_management
      - RUST_LOG=trace
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - RPC_SERVER_ADDRESS=0.0.0.0:5000
      - ENABLE_CORS=true
  api-server:
    image: flotte-docker-registry.spdns.org/apollo-server
    links:
      - "db:database"
      - "user-management:um"
    restart: unless-stopped
    environment:
      - RPC_HOST=um:5000
      - DATABASE_URL=postgres://fapi:passwordofapiserver@database/flotte_api
      - NODE_ENV=nodevelop
  frontend:
      image: flotte-docker-registry.spdns.org/frontend-server
  proxy:
    image: staticfloat/nginx-certbot
    links:
      - "frontend:frontend"
      - "api-server:api-server"
      - "user-management:user-management"
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "your_email@mail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro
volumes:
  database-volume: {}
  letsencrypt:
